acl internal {
    192.168.1.0/24;
};

tls cloudflare-tls {
    remote-hostname "one.one.one.one";
};

tls quad9-tls {
    remote-hostname "dns.quad9.net";
}; 

options {
    directory "/var/cache/bind";

    version "not currently available";

    recursion yes;
    forward only;

    allow-query { internal; };
    allow-recursion { internal; };
    allow-query-cache { internal; };

    forwarders port 853 {
        1.1.1.1 tls cloudflare-tls;
        1.0.0.1 tls cloudflare-tls;

        9.9.9.9 tls quad9-tls;
        149.112.112.112 tls quad9-tls;
    };
};

zone "home.olivando.me" {
    type forward;

    forwarders {
        192.168.1.253 port 5053;
        192.168.1.252 port 5053;
    };

    forward only;
};

statistics-channels { 
    inet 0.0.0.0 port 80; 
};

logging {
    channel default_log {
        file "/var/log/bind/default.log" versions 3 size 10m;
        severity info;
        print-time yes;
        print-severity yes;
        print-category yes;
    };
};